version: '3.8'
services:
  mongo-repl:
    image: mongo:6.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data/mongo:/data/db
      - ./backend/docker/init-rs.js:/docker-entrypoint-initdb.d/init-rs.js:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
